FROM graze/composer

RUN apk add --no-cache \
    php7 \
    php7-intl \
    php7-pcntl \
    php7-tokenizer \
    php7-fileinfo \
    php7-simplexml \
    php7-dom \
    php7-gd \
    php7-xml \
    php7-xmlreader \
    php7-xmlwriter \
    php7-zip \
    php7-bcmath